import { localizeText } from './localizeText';
import * as settings from './settings';
import { pryv } from './patchedPryv';
import { HDSModel } from './HDSModel/HDSModel';
import * as appTemplates from './appTemplates/appTemplates';
import * as logger from './logger';
import { HDSService } from './HDSService';
import * as HDSModelInitAndSingleton from './HDSModel/HDSModelInitAndSingleton';
import * as toolkit from './toolkit';
import { durationToSeconds, durationToLabel } from './utils/duration';
import { computeReminders } from './HDSModel/reminders';
import { eventToShortText, formatEventDate } from './HDSModel/eventToShortText';
import { MonitorScope } from './MonitorScope';
import { HDSSettings, SETTING_TYPES } from './settings/HDSSettings';
import { HDSModelConversions } from './HDSModel/HDSModel-Conversions';
export type { MonitorScopeConfig, MonitorScopeCallbacks } from './MonitorScope';
export type { ReminderConfig } from './HDSModel/HDSItemDef';
export type { ReminderSource, ReminderStatus } from './HDSModel/reminders';
export type { SettingKey, SettingsValues, DateFormat, UnitSystem, Theme } from './settings/HDSSettings';
export declare const model: HDSModel;
export declare const getHDSModel: typeof HDSModelInitAndSingleton.getModel;
export declare const initHDSModel: typeof HDSModelInitAndSingleton.initHDSModel;
export { pryv, settings, HDSService, HDSModel, appTemplates, localizeText, localizeText as l, toolkit, logger, durationToSeconds, durationToLabel, computeReminders, eventToShortText, formatEventDate, MonitorScope, HDSSettings, SETTING_TYPES, HDSModelConversions };
declare const HDSLib: {
    getHDSModel: typeof HDSModelInitAndSingleton.getModel;
    initHDSModel: typeof HDSModelInitAndSingleton.initHDSModel;
    pryv: typeof pryv;
    settings: typeof settings;
    HDSService: typeof HDSService;
    HDSModel: typeof HDSModel;
    appTemplates: typeof appTemplates;
    localizeText: typeof localizeText;
    l: typeof localizeText;
    toolkit: typeof toolkit;
    logger: typeof logger;
    durationToSeconds: typeof durationToSeconds;
    durationToLabel: typeof durationToLabel;
    computeReminders: typeof computeReminders;
    eventToShortText: typeof eventToShortText;
    formatEventDate: typeof formatEventDate;
    MonitorScope: typeof MonitorScope;
    HDSSettings: {
        hookToApplication(app: appTemplates.Application): Promise<void>;
        hookToConnection(connection: pryv.Connection, streamId: string): Promise<void>;
        get<K extends import("./settings/HDSSettings").SettingKey>(key: K): import("./settings/HDSSettings").SettingsValues[K];
        getAll(): Readonly<import("./settings/HDSSettings").SettingsValues>;
        set<K extends import("./settings/HDSSettings").SettingKey>(key: K, value: import("./settings/HDSSettings").SettingsValues[K]): Promise<void>;
        readonly isHooked: boolean;
        reload(): Promise<void>;
        unhook(): void;
    };
    SETTING_TYPES: {
        readonly preferredLocales: "settings/preferredLocales";
        readonly theme: "settings/theme";
        readonly timezone: "settings/timezone";
        readonly dateFormat: "settings/dateFormat";
        readonly unitSystem: "settings/unitSystem";
        readonly displayName: "settings/displayName";
    };
    HDSModelConversions: typeof HDSModelConversions;
};
export default HDSLib;
//# sourceMappingURL=index.d.ts.map